### PR TITLE
change omgwtfnzbs TLD from .me to .org, bump version

### PR DESCRIPTION
**Pull request by hollanbm**
change omgwtfnzbs TLD from .me to .org, bump version #4

### CODE REVIEW

**Comment by hollanbm** [comment]
@bertvandepoel Would appreciate some eyes on this.

Can I submit the updated version to firefox, or do you need to do that?

**Comment by adamw1548** [comment]
@bertvandepoel what does it take to get this integrated into a new extension?

**Comment by hollanbm** [comment]
@adamw1548 I've given up, I went ahead and submitted my fork to firefox as a new addon.

Will update with the URL when done

**Comment by bertvandepoel** [comment]
Hey everyone. Sorry for getting back to you extremely late. I've had some health and personal issues keeping me from doing lots of FOSS stuff. This extension has been on my todo for May but I haven't gotten around to it. As my repo is currently also commits behind on the mother chrome extension repo, I would want to review their changes before bumping version numbers to make sure things don't get confusing. I am very sorry that this has been a source of frustration for everyone. I really wish the original author of the chrome extension was willing to merge code bases (it's possible) and that way maintenance wouldn't be such a big thing. I also don't have access to many of the indexers people use, so testing is complicated. I do hope your fork does well, obviously, but I still plan to get around to this.

**Comment by adamw1548** [comment]
> Hey everyone. Sorry for getting back to you extremely late. I've had some health and personal issues keeping me from doing lots of FOSS stuff. This extension has been on my todo for May but I haven't gotten around to it. As my repo is currently also commits behind on the mother chrome extension repo, I would want to review their changes before bumping version numbers to make sure things don't get confusing. I am very sorry that this has been a source of frustration for everyone. I really wish the original author of the chrome extension was willing to merge code bases (it's possible) and that way maintenance wouldn't be such a big thing. I also don't have access to many of the indexers people use, so testing is complicated. I do hope your fork does well, obviously, but I still plan to get around to this.

Thanks for the update and wish you the best.

**Comment by hollanbm** [comment]
https://addons.mozilla.org/en-US/firefox/addon/sabconnect-redux/

**Comment by adamw1548** [comment]
> https://addons.mozilla.org/en-US/firefox/addon/sabconnect-redux/

confirmed working! thanks again.

**Pull request closed without merging**
